### ISSUE TITLE
Antwortmöglichkeit nur für registrierte Nutzer

### ISSUE THREAD

**Issue by Jozys** [SE-TINF22B2/G6-SimpleQ#19]
**Beschreibung**

Das System muss nur registrieren Nutzern die Möglichkeit bieten auf Fragen zu antworten. 
Bei unregistrierten Usern führt der Link zum Antworten auf eine Seite zum registrieren.

---

**Abnahmekriterien**

- [x] Als registrierter User wird mir bei einer Frage die Möglichkeit zu Antworten graphisch angezeigt.
- [x] Wenn ein registrierter User antwortet, wird die Antwort für alle User sichtbar.
- [ ] Als unregistrierter User wird mir die Antwortmöglichkeit gekennzeichnet und verlinkt auf  #61 .

---

**Arbeitspakete**
- [x] Implementation der Logik im Frontend #105
- [x] Überprüfung der Anfrage im Backend #103
